### PR TITLE
Fetch unemployment and household data to find duplicate places

### PR DESCRIPTION
**Pull request by shifucun**
This change is [Reviewable](https://reviewable.io/reviews/datacommonsorg/tools/89)

### CODE REVIEW

**Review by pradh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/tools/89)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @shifucun)

___
*[find-duplicate-places/main.py, line 70 at r1](https://reviewable.io/reviews/datacommonsorg/tools/89#-MR_jLwYBrf8KC9aDUwH:-MR_jLwZC8VI_1ZoPF6X:by6l047) ([raw file](https://github.com/datacommonsorg/tools/blob/5cf0f219b966c5a9a99779899c2299721e906557/find-duplicate-places/main.py#L70)):*
> ```Python
>             place = c[1]
>             parts = c[0].split(" ")
>             # This is the similarity checkfor name , can expand this to handle more cases.
> ```

nit: check for
___
*[find-duplicate-places/main.py, line 93 at r1](https://reviewable.io/reviews/datacommonsorg/tools/89#-MR_jWSN6eiCO5r08kvg:-MR_jWSN6eiCO5r08kvh:b-xb6ogq) ([raw file](https://github.com/datacommonsorg/tools/blob/5cf0f219b966c5a9a99779899c2299721e906557/find-duplicate-places/main.py#L93)):*
> ```Python
>                 current = c
>                 token = parts[0]
>                 first = True
> ```

Skip checking in CSV file ?

**Review by pradh — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/tools/89)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @shifucun)

**Review by shifucun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/tools/89)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @pradh)

___
*[find-duplicate-places/main.py, line 93 at r1](https://reviewable.io/reviews/datacommonsorg/tools/89#-MR_jWSN6eiCO5r08kvg:-MRkjgWQ6ChEcy5snylh:b-2wfq3) ([raw file](https://github.com/datacommonsorg/tools/blob/5cf0f219b966c5a9a99779899c2299721e906557/find-duplicate-places/main.py#L93)):*
<details><summary><i>Previously, pradh (Prashanth R) wrote…</i></summary><blockquote>

Skip checking in CSV file ?
</blockquote></details>

do not quite understand..

**Review by pradh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/tools/89)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @shifucun)

___
*[find-duplicate-places/main.py, line 93 at r1](https://reviewable.io/reviews/datacommonsorg/tools/89#-MR_jWSN6eiCO5r08kvg:-MRkkgJ949PMVfsfkV73:bw09p78) ([raw file](https://github.com/datacommonsorg/tools/blob/5cf0f219b966c5a9a99779899c2299721e906557/find-duplicate-places/main.py#L93)):*
<details><summary><i>Previously, shifucun (Bo Xu) wrote…</i></summary><blockquote>

do not quite understand..
</blockquote></details>

don't add the csv to github?

**Review by pradh — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/tools/89#-:-MRkkoPr3Xr07nQAMCb6:bb6ywmx)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @shifucun)

**Comment by shifucun** [comment]
> > _[Reviewable](https://reviewable.io/reviews/datacommonsorg/tools/89)_ status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @shifucun)
> 
> _[find-duplicate-places/main.py, line 93 at r1](https://reviewable.io/reviews/datacommonsorg/tools/89#-MR_jWSN6eiCO5r08kvg:-MRkkgJ949PMVfsfkV73:bw09p78) ([raw file](https://github.com/datacommonsorg/tools/blob/5cf0f219b966c5a9a99779899c2299721e906557/find-duplicate-places/main.py#L93)):_
> 
> Previously, shifucun (Bo Xu) wrote…
> don't add the csv to github?

done

**Review by pradh — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/datacommonsorg/tools/89)* status: 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
